language: node_js

node_js:
  - '8'

sudo: required

services:
  - docker

after_deploy:
  - echo "done deploying"

deploy:
  provider: elasticbeanstalk
  access_key_id: ''
  secret_access_key:
    secure: ''
  region: 'us-east-2'
  app: 'eb1'
  env: 'Eb1-env'
  bucket_name: 'elasticbeanstalk-us-east-2-'
  on:
    branch: master
