name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Create env file
        run: |
          touch .env
          echo NODE_ENV="production" >> .env
          echo MONGODB_URI=${{ secrets.MONGODB_URI }} >> .env
          cat .env

      - name: Generate deployment package
        run: zip -r deploy.zip * -x "**node_modules**"

      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: '${{ steps.current-time.outputs.time }}'
          replace-with: '-'
          flags: 'g'

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          region: us-east-2
          application_name: eb1
          environment_name: Eb1-env
          version_label: 'my-app-${{steps.format-time.outputs.replaced}}'
          deployment_package: deploy.zip

      - name: Deployed!
        run: echo App deployed to ELB
