name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Create env file
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: |
          touch .env
          echo "NODE_ENV=production" >> .env
          echo "MONGODB_URI=$MONGODB_URI" >> .env
          cat .env

      - name: list files
        run: ls -lah

      - name: cat
        run: cat ".env"

      - name: Generate deployment package
        run: zip -r deploy.zip . -x "**node_modules**" -x ".git/\*"

      - name: ziplist
        run: unzip -vl "deploy.zip"